prompt Importing table sttbs_account...
set feedback off
set define off
insert into sttbs_account (AC_GL_NO, PKEY, BRANCH_CODE, AC_GL_CCY, AC_OR_GL, CUST_NO, GL_ACLASS_TYPE, AC_GL_DESC, AC_STAT_NO_CR, AC_STAT_NO_DR, GL_STAT_BLOCKED, AC_STAT_STOP_PAY, AC_STAT_DORMANT, AC_STAT_FROZEN, GL_STAT_DE_POST, GL_BRANCH_RES, GL_CCY_RES, ALT_AC_NO, CUST_NAME1, GL_CATEGORY, RECON_TYPE, AC_CLASS, AC_NATURAL_GL, CUSTOMER_CAT, OFFLINE_LIMIT, AC_GL_REC_STATUS, AC_OPEN_DATE, AUTH_STAT, NATIVE, AC_NATIVE, IBAN_AC_NO, DORMANT_PARAM, ONCE_AUTH)
values ('0303830101944254', '030928054', '030', 'XAF', 'A', '019442', '6', 'EGUTE DIEUDONNE ANJONEK SAVINGS ACCOUNT INDIVIDUAL NON SALARY ', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y', null, null, '000303738030719894', 'EGUTE DIEUDONNE ANJONEK', '2', null, '383', '373001000', '83', null, 'O', to_date('03-01-2011', 'dd-mm-yyyy'), 'A', null, null, null, 'C', 'Y');

prompt Done.
