CREATE TABLESPACE FCCDATASML 
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCDATASML01.DBF' SIZE 3096M AUTOEXTEND OFF 
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCINDXSML 
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCINDXSML01.DBF' SIZE 1705M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCDATAMED 
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCDATAMED01.DBF' SIZE 3096M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCINDXMED DATAFILE 
  '/u01/app/oracle/oradata/NFCSUP/FCCINDXMED01.DBF' SIZE 1522M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCDATALAR 
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCDATALAR01.DBF' SIZE 17120M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCINDXLAR 
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCINDXLAR01.DBF' SIZE 32767M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
----
CREATE TABLESPACE FCCDATAXL --ok
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCDATAXL01.DBF' SIZE 30768M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

ALTER TABLESPACE FCCDATAXL ADD DATAFILE  '/u01/app/oracle/oradata/NFCSUP/FCCDATAXL02.DBF' SIZE 30768M AUTOEXTEND OFF 
      NEXT 512K
      MAXSIZE 250M;



CREATE TABLESPACE FCCINDXXL --ok
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCCINDXXL01.DBF' SIZE 30768M AUTOEXTEND OFF,
  '/u01/app/oracle/oradata/NFCSUP/FCCINDXXL02.DBF' SIZE 3328M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE FCCDFLT --ok
DATAFILE '/u01/app/oracle/FCCDFLT01.DBF' SIZE 30768M AUTOEXTEND OFF 
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

ALTER TABLESPACE FCCDFLT ADD DATAFILE '/u01/app/oracle/FCCDFLT02.DBF' SIZE 30768M 
AUTOEXTEND OFF;--ok

ALTER TABLESPACE FCCDFLT ADD DATAFILE '/u01/app/oracle/oradata/FCRPUBS/FCCDFLT03.DBF' SIZE 30768M 
AUTOEXTEND OFF       
NEXT 512K       
MAXSIZE 250M;--ok



CREATE TABLESPACE FCUBS --ok
DATAFILE '/u01/app/oracle/oradata/NFCSUP/FCUBS01.DBF' SIZE 8192M AUTOEXTEND OFF,
'/u01/app/oracle/oradata/NFCSUP/FCUBS02.DBF' SIZE 8192M AUTOEXTEND OFF,
'/u01/app/oracle/oradata/NFCSUP/FCUBS03.DBF' SIZE 1024M AUTOEXTEND OFF
LOGGING ONLINE PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



ALTER DATABASE DATAFILE '/u01/app/oracle/oradata/NFCSUP/system01.dbf' RESIZE 32767M;--ok


ALTER TABLESPACE SYSTEM ADD DATAFILE '/u01/app/oracle/oradata/NFCSUP/system02.dbf' SIZE 32767M--ok
      AUTOEXTEND OFF
      NEXT 512K
      MAXSIZE 250M;

ALTER DATABASE DATAFILE '/u01/app/oracle/oradata/NFCSUP/undotbs01.dbf' RESIZE 32767M;--ok

ALTER DATABASE DATAFILE '/u01/app/oracle/oradata/NFCSUP/temp01.dbf' RESIZE 3096M;

ALTER TABLESPACE TEMP ADD TEMPFILE '/u01/app/oracle/oradata/NFCSUP/temp02.dbf' SIZE 3096M
      AUTOEXTEND OFF
      NEXT 512K
      MAXSIZE 250M;
	  
	  
	  
ALTER TABLESPACE FCCDFLT ADD DATAFILE '/u02/app/oracle/oradata/FCRPUBS/FCCDFLT15.dbf' SIZE 32767M--ok
      AUTOEXTEND OFF
      NEXT 512K
      MAXSIZE 250M;	   

ALTER TABLESPACE FCCDFLT ADD DATAFILE '/u02/app/oracle/oradata/FCRPUBS/FCCDFLT19.dbf' SIZE 32767M AUTOEXTEND OFF;
      NEXT 512K
      MAXSIZE 250M;	   
