grant select on dba_jobs to XAFNFC;
grant select on dba_jobs_running to XAFNFC;
grant select on v_$database to XAFNFC;
grant select on v_$nls_parameters to XAFNFC;
grant select on v_$parameter to XAFNFC;
grant select on v_$process to XAFNFC;
grant select on v_$session to XAFNFC;
grant select on v_$timer to XAFNFC;
grant select on v_$instance to XAFNFC;
grant create database link to XAFNFC;
grant create library to  XAFNFC;
grant create materialized view to XAFNFC;
grant create procedure to XAFNFC;
grant create sequence to XAFNFC;
grant create session to XAFNFC;
grant create synonym to XAFNFC;
grant create table to XAFNFC;
grant create trigger to XAFNFC;
grant create type to XAFNFC;
grant create view to XAFNFC;
grant execute on dbms_alert to XAFNFC;
grant execute on dbms_application_info to XAFNFC;
grant execute on dbms_aq to XAFNFC;
grant execute on dbms_aqadm to XAFNFC;
grant execute on dbms_defer to XAFNFC;
grant execute on dbms_defer_query to XAFNFC;
grant execute on dbms_defer_sys to XAFNFC;
grant execute on dbms_job to XAFNFC;
grant execute on dbms_lock to XAFNFC;
grant execute on dbms_pipe to XAFNFC;
grant execute on dbms_refresh to XAFNFC;
grant execute on dbms_rls to XAFNFC;
grant execute on dbms_shared_pool to XAFNFC;
grant execute on dbms_sql to XAFNFC;
grant execute on utl_file to XAFNFC;
grant dba to XAFNFC;
EXEC DBMS_JAVA.grant_permission('XAFNFC', 'java.io.FilePermission', '*', 'read , execute');
EXEC DBMS_JAVA.grant_permission('XAFNFC', 'SYS:java.lang.RuntimePermission', 'writeFileDescriptor', '*');
EXEC DBMS_JAVA.grant_permission('XAFNFC', 'SYS:java.lang.RuntimePermission', 'readFileDescriptor', '*');
GRANT JAVAUSERPRIV TO XAFNFC;
EXEC dbms_java.grant_permission( 'NFCSUP', 'SYS:java.net.SocketPermission', '172.20.50.4:7001', 'connect,resolve' );

