CREATE TABLE CLTB_ACC_COMP_BAL_BREAKUP_30NOV AS SELECT * FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP WHERE account_number='050M03K121440001' ;


DECLARE
BEGIN
FOR I IN (SELECT ACCOUNT_NUMBER,SUM(BALANCE),SUM(LCY_BALANCE) FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP where account_number='050M03K121440001' and gl_type='C' GROUP BY ACCOUNT_NUMBER )
LOOP
update CLTB_ACCOUNT_COMP_BAL_BREAKUP set BALANCE = I.BALANCE ,set LCY_BALANCE =I.LCY_BALANCE , STATUS_CODE='DOC3'
where account_number=I.ACCOUNT_NUMBER
and gl_type='C'
and component='MAIN_INT';

DELETE FROM CLTB_ACCOUNT_COMP_BAL_BREAKUP where account_number=I.ACCOUNT_NUMBER
and gl_type='C'
AND STATUS_CODE='NORM'
and component='MAIN_INT';

END LOOP;
END;

UPDATE CLTB_ACCOUNT_MASTER K SET K.USER_DEFINED_STATUS='DOC3'
WHERE ACCOUNT_NUMBER='050M03K121440001';

COMMIT;
