SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '020' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '021' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '022' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '023' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '024' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '030' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '031' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '032' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '040' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '041' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '042' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '043' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '050' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;
SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere from xafnfc.sttm_customer c , sttm_cust_personal p where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.local_branch = '051' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  order by c.customer_name1;

SELECT  c.local_branch,count(*)
from xafnfc.sttm_customer c , sttm_cust_personal p 
where p.customer_no = c.customer_no and  c.customer_type ='I' and c.record_stat ='O' and p.ppt_iss_date is  null and c.customer_type ='I' and c.record_stat ='O' and c.customer_no in (select a.cust_no from sttm_cust_account a WHERE a.record_stat ='O' )  
group by c.local_branch order by c.local_branch;

-- Pending Records
SELECT c.local_branch,count(*) 
from xafnfc.sttm_customer c , sttm_cust_personal p 
where p.customer_no = c.customer_no
and p.ppt_iss_date is null 
and c.customer_type ='I' and c.record_stat ='O'
group by c.local_branch order by c.local_branch;

-- Validated Redords

SELECT * from control_cif_cip;


SELECT c.local_branch,c.customer_no as IdInterneClt,c.customer_name1,p.p_national_id,null as nom_naissance,null as prenom,null as Nom_marital,null as num_piece,null as date_delivrance,null as lieu_delivrance,null as date_validite,null as Nom_Du_Pere,null as Prenom_pere,null as nom_naissance_mere,null as prenom_mere 
from xafnfc.sttm_customer c , sttm_cust_personal p 
where p.customer_no = c.customer_no 
and  c.customer_type ='I' 
and c.record_stat ='O' 
and p.ppt_iss_date is  null 
and c.customer_type ='I' and c.record_stat ='O'
order by c.local_branch ,c.customer_name1;

SELECT  p.p_national_id,p.passport_no,p.ppt_iss_date from sttm_cust_personal p WHERE p.p_national_id like 'CM%'

update sttm_cust_personal p set p.p_national_id = p.passport_no WHERE p.passport_no is not null and p.p_national_id like 'CM%'

(--select cm.customer_no
select cm.local_branch,cm.customer_no,cm.customer_name1,cm.address_line1,cd.customer_no,cd.customer_name1,cd.address_line1,cd.address_line3
from xafnfc.sttm_customer cm 
join (SELECT cu.customer_no,cu.customer_name1,cu.address_line1,cu.address_line3,ud.field_val_8 Mandator_no
FROM xafnfc.sttm_customer cu ,xafnfc.CSTM_FUNCTION_USERDEF_FIELDS ud  
WHERE substr(ud.rec_key,1,6) = cu.customer_no
and ud.field_val_8 is not null) cd on cd.Mandator_no = cm.customer_no )
