ACCEPT ACC PROMPT 'PLS ENTER THE ACCOUNT NO. ==> '
SET ARRAY 1
SET HEAD ON
SET COLSEP ";"
SET FEEDBACK ON
SET LINESIZE 10000
SET PAGESIZE 50000
SET LONG 10000
SET ECHO ON
SET TRIMSPOOL ON
SET NUMFORMAT 999999999999999999999.99999

SPOOL C:\AC_DET.SPL

SELECT * FROM STTMS_CUST_ACCOUNT WHERE CUST_AC_NO = '&ACC';

SELECT * FROM STTBS_ACCOUNT WHERE AC_GL_NO = '&ACC';

SELECT * FROM ACVWS_ALL_AC_ENTRIES WHERE AC_NO = '&ACC';

SELECT * FROM ACTB_DAILY_LOG WHERE AC_NO = '&ACC';

SELECT * FROM ACTBS_ACCBAL_HISTORY WHERE ACCOUNT = '&ACC';

SELECT * FROM CATMS_AMOUNT_BLOCKS WHERE ACCOUNT  ='&ACC';

SELECT * FROM ACTBS_FUNCOL WHERE ACCOUNT  ='&ACC';

SELECT SUM(DECODE(DRCR_IND,'D',-LCY_AMOUNT,LCY_AMOUNT)) FROM ACVW_ALL_AC_ENTRIES WHERE AC_NO = '&ACC';

SELECT * FROM ACTBS_VD_BAL WHERE ACC = '&ACC';

SELECT * FROM STTMS_ACCOUNT_BAL_TOV WHERE CUST_AC_NO = '&ACC';

SELECT * FROM ACTB_DAILY_GHOST_LOG WHERE AC_NO = '&ACC';

SELECT * FROM STTM_ACCOUNT_CLASS WHERE ACCOUNT_CLASS IN (SELECT ACCOUNT_CLASS FROM STTM_CUST_ACCOUNT WHERE CUST_AC_NO = '&ACC');


SELECT * FROM ICTBS_DR_INT_ERR WHERE ACC = '&ACC';

SELECT * FROM STTM_CUST_ACCOUNT_DORMANCY WHERE CUST_AC_NO = '&ACC';

SELECT * FROM STTM_TRN_CODE;

SELECT * FROM STTB_RECORD_LOG WHERE KEY_ID LIKE '~STTM_CUST_ACCOUNT~' || '%' || '~' || '&ACC' || '~';

SELECT * FROM STTB_FIELD_LOG WHERE DETAIL_KEY LIKE '~STTM_CUST_ACCOUNT~' || '%' || '~' || '&ACC' || '~';

SELECT * FROM STTB_RECORD_LOG_HIST WHERE KEY_ID LIKE '~STTM_CUST_ACCOUNT~' || '%' || '~' || '&ACC' || '~';

SELECT * FROM STTB_FIELD_LOG_HIST WHERE KEY_ID LIKE '~STTM_CUST_ACCOUNT~' || '%' || '~' || '&ACC' || '~';

SPOOL OFF
