ACCEPT BRN PROMPT 'Enter Branch Code => '
ACCEPT ACC PROMPT 'Enter Customer Account => '

set array 1
set head on
set colsep ";"
set feedback on
set line 10000
set pagesize 100000
set echo on
set trimspool on

spool C:\CASA_Details.spl

PROMPT
SHOW USER;

PROMPT
PROMPT STTMS_CUST_ACCOUNT
SELECT *
  FROM STTMS_CUST_ACCOUNT
 WHERE BRANCH_CODE = '&BRN'
   AND CUST_AC_NO = '&ACC';

PROMPT
PROMPT STTBS_ACCOUNT
SELECT *
  FROM STTBS_ACCOUNT
 WHERE BRANCH_CODE = '&BRN'
   AND AC_GL_NO = '&ACC';

PROMPT
SELECT *
  FROM STTMS_CUSTOMER
 WHERE CUSTOMER_NO IN
       (SELECT CUST_NO FROM STTMS_CUST_ACCOUNT WHERE CUST_AC_NO = '&ACC');

PROMPT
PROMPT STTM_ACCOUNT_CLASS
SELECT *
  FROM STTM_ACCOUNT_CLASS
 WHERE ACCOUNT_CLASS IN (SELECT ACCOUNT_CLASS
                           FROM STTMS_CUST_ACCOUNT
                          WHERE BRANCH_CODE = '&BRN'
                            AND CUST_AC_NO = '&ACC');

PROMPT
PROMPT ACVWS_ALL_AC_ENTRIES
SELECT * FROM ACVWS_ALL_AC_ENTRIES WHERE AC_NO = '&ACC' ORDER BY 2;

PROMPT
PROMPT ACTB_DAILY_LOG
SELECT * FROM ACTB_DAILY_LOG WHERE AC_NO = '&ACC' ORDER BY AC_ENTRY_SR_NO;

PROMPT
PROMPT ACTBS_ACCBAL_HISTORY
SELECT *
  FROM ACTBS_ACCBAL_HISTORY
 WHERE BRANCH_CODE = '&BRN'
   AND ACCOUNT = '&ACC'
 ORDER BY BKG_DATE;

PROMPT
PROMPT ACTBS_VD_BAL 
SELECT *
  FROM ACTBS_VD_BAL
 WHERE BRN = '&BRN'
   AND ACC = '&ACC'
 ORDER BY VAL_DT;

PROMPT
PROMPT CATM_CHECK_BOOK
SELECT *
  FROM CATM_CHECK_BOOK
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC'
 ORDER BY 1, 2, 3;

PROMPT
PROMPT CATM_CHECK_DETAILS
SELECT *
  FROM CATM_CHECK_DETAILS
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC'
 ORDER BY 1, 2, 3, 4;

PROMPT
PROMPT CATMS_UNRECONCILED_INSTR
SELECT *
  FROM CATMS_UNRECONCILED_INSTR
 WHERE BRANCH_CODE = '&BRN'
   AND ACCOUNT_NUMBER = '&ACC';

PROMPT
PROMPT CATMS_STOP_PAYMENTS
SELECT *
  FROM CATMS_STOP_PAYMENTS
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC';

PROMPT
PROMPT CATMS_AMOUNT_BLOCKS
SELECT *
  FROM CATMS_AMOUNT_BLOCKS
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC';

PROMPT
PROMPT CSTB_AUTO_SETTLE_BLOCK
SELECT *
  FROM CSTB_AUTO_SETTLE_BLOCK
 WHERE ACCOUNT_BR = '&BRN'
   AND ACCOUNT_NO = '&ACC'
 ORDER BY MODULE, CONTRACT_REF_NO, BOOK_DATE;

PROMPT
PROMPT ACTBS_FUNCOL
SELECT *
  FROM ACTBS_FUNCOL
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC'
 ORDER BY TRN_DT, AVAILABLEDATE;

PROMPT
PROMPT ACTBS_FUNCOL_HISTORY
SELECT *
  FROM ACTBS_FUNCOL_HISTORY
 WHERE BRANCH = '&BRN'
   AND ACCOUNT = '&ACC'
 ORDER BY TRN_DT, AVAILABLEDATE;

PROMPT
PROMPT ACVW_ALL_AC_ENTRIES-SUM
SELECT SUM(DECODE(DRCR_IND, 'D', -LCY_AMOUNT, LCY_AMOUNT)) ACC_BALANCE
  FROM ACVW_ALL_AC_ENTRIES
 WHERE AC_NO = '&ACC';

PROMPT
PROMPT FBTB_TXNLOG_MASTER
SELECT *
  FROM FBTB_TXNLOG_MASTER
 WHERE XREFID IN
       (SELECT DISTINCT EXTERNAL_REF_NO
          FROM ACVW_ALL_AC_ENTRIES
         WHERE EXTERNAL_REF_NO LIKE 'FJB%'
           AND (AC_NO = '&ACC' OR RELATED_ACCOUNT = '&ACC'));

PROMPT
PROMPT FBTB_TXNLOG_MASTER_HIST
SELECT *
  FROM FBTB_TXNLOG_MASTER_HIST
 WHERE XREFID IN
       (SELECT DISTINCT EXTERNAL_REF_NO
          FROM ACVW_ALL_AC_ENTRIES
         WHERE EXTERNAL_REF_NO LIKE 'FJB%'
           AND (AC_NO = '&ACC' OR RELATED_ACCOUNT = '&ACC'));

PROMPT
PROMPT FBTB_TXNLOG_DETAILS
SELECT *
  FROM FBTB_TXNLOG_DETAILS
 WHERE XREFID IN
       (SELECT DISTINCT EXTERNAL_REF_NO
          FROM ACVW_ALL_AC_ENTRIES
         WHERE EXTERNAL_REF_NO LIKE 'FJB%'
           AND (AC_NO = '&ACC' OR RELATED_ACCOUNT = '&ACC'));

PROMPT
PROMPT FBTB_TXNLOG_DETAILS_HIST
SELECT *
  FROM FBTB_TXNLOG_DETAILS_HIST
 WHERE XREFID IN
       (SELECT DISTINCT EXTERNAL_REF_NO
          FROM ACVW_ALL_AC_ENTRIES
         WHERE EXTERNAL_REF_NO LIKE 'FJB%'
           AND (AC_NO = '&ACC' OR RELATED_ACCOUNT = '&ACC'));

PROMPT
PROMPT STTB_RECORD_LOG
SELECT *
  FROM STTB_RECORD_LOG
 WHERE KEY_ID LIKE '%' || '&ACC' || '%'
 ORDER BY MOD_NO DESC;

PROMPT
PROMPT STTB_RECORD_LOG_HIST
SELECT *
  FROM STTB_RECORD_LOG_HIST
 WHERE KEY_ID LIKE '%' || '&ACC' || '%'
 ORDER BY MOD_NO DESC;

PROMPT
PROMPT STTB_FIELD_LOG
SELECT *
  FROM STTB_FIELD_LOG
 WHERE KEY_ID LIKE '%' || '&ACC' || '%'
 ORDER BY MOD_NO DESC;

PROMPT
PROMPT STTB_FIELD_LOG_HIST
SELECT *
  FROM STTB_FIELD_LOG_HIST
 WHERE KEY_ID LIKE '%' || '&ACC' || '%'
 ORDER BY MOD_NO DESC;

PROMPT
PROMPT STTB_CUST_AC_CLOSURE
SELECT *
  FROM STTB_CUST_AC_CLOSURE
 WHERE BRANCH_CODE = '&BRN'
   AND AC_NO = '&ACC';

PROMPT
SPOOL OFF