SELECT * FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY');
SELECT * FROM GETM_FACILITY_BLOCK WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_BRN_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_CCY_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_CHARGE WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_COVENANT WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_CUST_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_EXPOSURE WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_EXP_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_OFF_LIMIT WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_PROD_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_SCHEDULES WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_SYSTEM_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_TENOR_REST WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_UDE_VALUES WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETM_FACILITY_VD_DETAILS WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));
SELECT * FROM GETB_POOL_LINK WHERE FACILITY_ID = (SELECT ID FROM GETM_FACILITY  WHERE LIAB_ID =(SELECT ID FROM GETM_LIAB WHERE LIAB_NO='&LIABILITY'));

