ACCEPT ACCOUNT PROMPT 'ENTER THE ACCOUNT >'
ACCEPT BRANCH  PROMPT 'ENTER THE BRANCH  >'
SET ARRAY 1
SET HEAD ON
SET FEEDBACK ON
SET LINE 10000
SET PAGESIZE 10000
SET ECHO ON
SET COLSEP ";"
SET TRIMSPOOL ON
SET NUMFORMAT 99999999999999999999.9999
SPOOL C:\IC_DETAILS.SPL

SELECT * FROM STTM_DATES WHERE BRANCH_CODE='&BRANCH';

PROMPT ICTMS_PRODUCT_DEFINITION
SELECT * FROM ICTMS_PRODUCT_DEFINITION
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PRODUCT_CODE
/

PROMPT ICTBS_ACC_PR
SELECT * FROM ICTBS_ACC_PR WHERE ACC = '&ACCOUNT'
/

PROMPT STTM_CUST_ACCOUNT_DORMANCY
SELECT * FROM STTM_CUST_ACCOUNT_DORMANCY WHERE cust_ac_no='&ACCOUNT'
/
PROMPT ACCPR HISTORY
SELECT * FROM ICTB_ACC_PR_HISTORY  WHERE ACC = '&ACCOUNT'
/

PROMPT ICVWS_ACC_PR
SELECT * FROM ICVWS_ACC_PR WHERE ACC = '&ACCOUNT'
/

PROMPT ACC_ACTION
SELECT * FROM ICTBS_ACC_ACTION WHERE ACC = '&ACCOUNT'
/


PROMPT ICTBS_MAINT_QUEUE
SELECT * FROM ICTBS_MAINT_QUEUE
WHERE MAINT_KEY LIKE '%&ACCOUNT%'
/

PROMPT ACTION LOG
SELECT * FROM ICTBS_ACTION_LOG
WHERE KEY_VAL LIKE '%&ACCOUNT%'
/

PROMPT ICVW_LINE_DET
SELECT * FROM ICVW_LINE_DET WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT';

PROMPT ENTRIES
SELECT * FROM ICTBS_ENTRIES WHERE ACC = '&ACCOUNT'
/
PROMPT ENTRIES HISTORY
SELECT * FROM ICTBS_ENTRIES_HISTORY WHERE ACC = '&ACCOUNT' ORDER BY ENT_DT
/

PROMPT VD_BAL
SELECT * FROM ACTBS_VD_BAL WHERE ACC = '&ACCOUNT'
ORDER BY VAL_DT
/

PROMPT IS_VALS
SELECT * FROM ICTBS_IS_VALS WHERE ACC = '&ACCOUNT'
/

PROMPT ACVW_ALL_AC_ENTRIES_IC
SELECT * FROM ACVWS_ALL_AC_ENTRIES WHERE AC_BRANCH='&BRANCH'
AND ( AC_NO = '&ACCOUNT' OR RELATED_ACCOUNT = '&ACCOUNT')
AND MODULE='IC'
ORDER BY TRN_DT DESC
/

PROMPT ACVW_ALL_AC_ENTRIES
SELECT * FROM ACVWS_ALL_AC_ENTRIES WHERE AC_BRANCH='&BRANCH'
AND ( AC_NO = '&ACCOUNT' OR RELATED_ACCOUNT = '&ACCOUNT')
ORDER BY TRN_DT DESC
/

PROMPT STTM_RD_PAYMENTS_DET
SELECT * FROM STTM_RD_PAYMENTS_DET WHERE BRANCH_CODE='&BRANCH' AND RD_AC_NO='&ACCOUNT'
ORDER BY TXN_DATE
/

PROMPT UDEVALS
SELECT * FROM ICTBS_UDEVALS WHERE COND_KEY LIKE '%'||(SELECT ACCOUNT_CLASS||CCY FROM STTM_CUST_ACCOUNT
                                                 WHERE CUST_AC_NO LIKE  '&ACCOUNT') ||'%'
/

PROMPT ICTBS_UDEVALS
SELECT * FROM ICTBS_UDEVALS
WHERE COND_KEY LIKE '%&ACCOUNT%' ORDER BY PROD 	,UDE_EFF_DT
/

PROMPT ICTBS_UDEVALS_HIST
SELECT * FROM ICTBS_UDEVALS_HISTORY
WHERE COND_KEY LIKE '%&ACCOUNT%' ORDER BY PROD,UDE_EFF_DT
/

PROMPT ICTMS_ACC
SELECT * FROM ICTMS_ACC WHERE ACC = '&ACCOUNT'
/
PROMPT ICTMS_ACC_PR
SELECT * FROM ICTMS_ACC_PR WHERE ACC = '&ACCOUNT'
/
PROMPT ACC_UDEVALS
SELECT * FROM ICTMS_ACC_UDEVALS WHERE ACC = '&ACCOUNT'
/

PROMPT ICTMS_PR_INT
SELECT * FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PRODUCT_CODE
/

PROMPT ICTBS_PR_INT_ACLASS
SELECT * FROM ICTMS_PR_INT_ACLASS
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PRODUCT_CODE
/

SELECT * FROM CSTMS_PRODUCT WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR
WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
/


SELECT * FROM ICVWS_ACC_SDE WHERE  BRN='&BRANCH' AND ACC = '&ACCOUNT'
/

PROMPT CUST_ACCOUNT
SELECT * FROM STTMS_CUST_ACCOUNT WHERE CUST_AC_NO = '&ACCOUNT'
/

SELECT * FROM STTMS_CUSTOMER WHERE CUSTOMER_NO IN ( SELECT CUST_NO FROM
STTMS_CUST_ACCOUNT WHERE CUST_AC_NO = '&ACCOUNT')
/

PROMPT STTBS_ACCOUNT
SELECT * FROM STTBS_ACCOUNT WHERE AC_GL_NO = '&ACCOUNT'
/

PROMPT ICTMS_ACC_EFFDT
SELECT * FROM ICTMS_ACC_EFFDT WHERE ACC = '&ACCOUNT'
/

PROMPT ICTBS_XLOG
SELECT * FROM ICTBS_XLOG  WHERE ACC = '&ACCOUNT'
/

PROMPT ICTBS_BOOK_ERR
SELECT * FROM ICTBS_BOOK_ERR  WHERE ACC = '&ACCOUNT'
/

PROMPT ICTBS_CALC_ERR
SELECT * FROM ICTBS_CALC_ERR  WHERE ACC = '&ACCOUNT'
/
PROMPT ICTBS_RESOLUTION_ERR
--SELECT * FROM ICTBS_RESOLUTION_ERROR
/

PROMPT CSTMS_PRODUCT_EVENT_ACCT_ENTRY
SELECT * FROM CSTMS_PRODUCT_EVENT_ACCT_ENTRY
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PRODUCT_CODE,EVENT_CODE, AMT_TAG, DR_CR_INDICATOR
/

PROMPT CSTMS_PRODUCT_ACCROLE
SELECT * FROM CSTMS_PRODUCT_ACCROLE
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PRODUCT_CODE
/

PROMPT ICTMS_BRANCH_PARAMETERS
SELECT * FROM ICTMS_BRANCH_PARAMETERS WHERE BRANCH_CODE = '&BRANCH'
/

PROPT CALC QUEUE
SELECT * FROM ICTBS_CALC_QUEUE
WHERE BRN ='&BRANCH'
AND ACC = '&ACCOUNT'
AND PROD IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
ORDER BY PROD
/

PROMPT ICTBS_ACQR

SELECT * FROM ICTBS_ACQUIRED_INTR WHERE CUST_AC_NO ='&ACCOUNT' AND BRANCH_CODE ='&BRANCH'
/

PROMPT ICTBS_ADJ_INTEREST

SELECT * FROM ICTBS_ADJ_INTEREST WHERE BRN='&BRANCH' AND ACC = '&ACCOUNT'
/
PROMPT ICTBS_ADJ_INTEREST_HISTORY

SELECT * FROM ICTBS_ADJ_INTEREST_HISTORY WHERE BRN='&BRANCH' AND ACC = '&ACCOUNT' ;

PROMPT ICTBS_ACQR HISTORY

SELECT * FROM ICTBS_ACQUIRED_INTR_HISTORY  WHERE CUST_AC_NO ='&ACCOUNT' AND BRANCH_CODE ='&BRANCH'
/

SELECT * FROM ICTBS_BACK_DATED_UDEVALS
WHERE COND_KEY LIKE '%'||(SELECT ACCOUNT_CLASS||CCY FROM STTM_CUST_ACCOUNT
                                                 WHERE CUST_AC_NO LIKE  '&ACCOUNT') ||'%'
/
SELECT * FROM ICTBS_BACK_DATED_UDEVALS
WHERE COND_KEY LIKE '%&ACCOUNT%'
/

PROMPT BACK VALUED EVENTS

SELECT * FROM ICTBS_BACK_DATED_EVENTS
WHERE ACC LIKE '&ACCOUNT'
/

PROMPT ICTBS_CONSOL_BD_BAL
SELECT C.* FROM ICTBS_CONSOL_BD_BAL C
WHERE EXISTS ( SELECT 1 FROM ICTMS_ACC M WHERE M.BRN = C.BRN AND M.CALC_ACC = C.ACC AND M.ACC = '&ACCOUNT')
/

PROMPT ICTBS_CONSOL_VD_BAL
SELECT C.* FROM ICTBS_CONSOL_VD_BAL C
WHERE EXISTS ( SELECT 1 FROM ICTMS_ACC M WHERE M.BRN = C.BRN AND M.CALC_ACC = C.ACC AND M.ACC = '&ACCOUNT')
/

PROMPT ICTB_RACR
SELECT * FROM ICTBS_RACR WHERE BRN = '&BRANCH' AND ACC = '&ACCOUNT'
/

PROMPT ICTMS_PR_CHG
SELECT * FROM ICTMS_PR_CHG WHERE PRODUCT_CODE  IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
/

PROMPT ICTMS_PRODUCT_DEFINITION
SELECT * FROM ICTMS_PRODUCT_DEFINITION WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT')
/

PROMPT ICTMS_PR_INT_UDEVALS
SELECT * FROM ICTMS_PR_INT_UDEVALS WHERE PRODUCT_CODE IN ( SELECT PROD FROM ICVWS_ACC_PR WHERE ACC ='&ACCOUNT')
/

PROMPT PR_INT_EFFDT
SELECT * FROM ICTMS_PR_INT_EFFDT WHERE PRODUCT_CODE IN ( SELECT PROD FROM ICVWS_ACC_PR WHERE ACC ='&ACCOUNT')
/
PROMPT 'ALL RULES LINKED TO THE ACCOUNT'

SELECT * FROM ICTMS_RULE WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_RULE_FRM WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_RULE_FRM_ELEMENTS WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_RULE_SDE WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_RULE_UDE WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTM_EXPR WHERE RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_IS_FMT_DESC WHERE  RULE_ID IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTMS_PR_INT WHERE RULE IN (SELECT RULE FROM ICTMS_PR_INT
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

PROMPT HOLIDAY

SELECT * FROM STTM_LCL_HOLIDAY WHERE BRANCH_CODE='&BRANCH' AND YEAR = ( SELECT TO_CHAR(TODAY,'YYYY')
FROM STTM_DATES WHERE BRANCH_CODE='&BRANCH');

SELECT * FROM STTM_TRN_CODE WHERE TRN_CODE IN
(SELECT   TRANSACTION_CODE FROM CSTMS_PRODUCT_EVENT_ACCT_ENTRY
WHERE PRODUCT_CODE IN (SELECT DISTINCT PROD FROM ICVWS_ACC_PR WHERE BRN ='&BRANCH' AND ACC = '&ACCOUNT'))
/

SELECT * FROM ICTBS_ITM_TOV WHERE ACC ='&ACCOUNT';

SELECT * FROM ICVW_LINE_DET  WHERE ACC ='&ACCOUNT'
/

SELECT * FROM ICTMS_RATE_DEF
WHERE RATE_CODE IN
	(
		SELECT RATE_CODE FROM ICTBS_UDEVALS
			WHERE COND_KEY LIKE '%'||(SELECT ACCOUNT_CLASS||CCY FROM STTM_CUST_ACCOUNT
                                                 WHERE CUST_AC_NO LIKE  '&ACCOUNT') ||'%'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTBS_UDEVALS
			WHERE COND_KEY LIKE '%&ACCOUNT%'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTMS_ACC_UDEVALS
			WHERE ACC = '&ACCOUNT'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTBS_UDEVALS_HISTORY
			WHERE COND_KEY LIKE '%&ACCOUNT%'
			AND RATE_CODE IS NOT NULL
	)
/

SELECT * FROM ICTMS_RATES WHERE RATE_CODE IN
	(
		SELECT RATE_CODE FROM ICTBS_UDEVALS
			WHERE COND_KEY LIKE '%'||(SELECT ACCOUNT_CLASS||CCY FROM STTM_CUST_ACCOUNT
                                                 WHERE CUST_AC_NO LIKE  '&ACCOUNT') ||'%'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTBS_UDEVALS
			WHERE COND_KEY LIKE '%&ACCOUNT%'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTMS_ACC_UDEVALS
			WHERE ACC = '&ACCOUNT'
			AND RATE_CODE IS NOT NULL
		UNION
		SELECT RATE_CODE FROM ICTBS_UDEVALS_HISTORY
			WHERE COND_KEY LIKE '%&ACCOUNT%'
			AND RATE_CODE IS NOT NULL
	)
/

SELECT * FROM STTM_ACCOUNT_CLASS
WHERE ACCOUNT_CLASS IN
(
SELECT ACLASS FROM ICTBS_ACC_PR
WHERE ACC = '&ACCOUNT'
);

SELECT * FROM ICTBS_DR_INT_ERR
WHERE ACC = '&ACCOUNT'
/

PROMPT ACTM_IB_SETUP
SELECT * FROM ACTM_IB_SETUP
/

PROMPT ACTM_IB_ROUTE
SELECT * FROM ACTB_IB_ROUTE
/

PROMPT ICTBS_ICALC_STMT
SELECT * FROM ICTBS_ICALC_STMT WHERE ACC = '&ACCOUNT'
/

PROMPT ICTB_ICALC_STMT_HIST
SELECT * FROM ICTB_ICALC_STMT_HIST WHERE ACC = '&ACCOUNT'
/

Prompt td details
SELECT * FROM ictm_td_details where acc='&account'
/

PROMPT NEWLY ADDED FOR CHARGE
SELECT * FROM ICTB_CHG_VAL WHERE ACC='&ACCOUNT'
/

SELECT * FROM ICTB_CHG_VAL_HISTORY WHERE ACC='&ACCOUNT'
/

PROMPT NEWLY ADDED FOR RD

SELECT * FROM STTMS_RD_PAYMENTS_DET WHERE BRANCH_CODE ='&BRANCH' AND  RD_AC_NO='&ACCOUNT'
/


PROMPT ICVW_VD_LINE_UTIL
SELECT * FROM  ICVW_VD_LINE_UTIL WHERE BRANCH_CODE = '&BRANCH' AND CUST_AC_NO='&ACCOUNT'
/

PROMPT ICVW_VD_LINE_DET
SELECT * FROM  ICVW_VD_LINE_DET WHERE BRANCH_CODE = '&BRANCH' AND CUST_AC_NO='&ACCOUNT'
/

PROMPT LMTBS_LIMIT_VDCHG_LOG
SELECT *
  FROM LMTBS_LIMIT_VDCHG_LOG
 WHERE CUST_ID IN (SELECT CUS.CUSTOMER_NO
                     FROM LMTMS_LIMITS LM, STTM_CUSTOMER CUS
                    WHERE INTEREST_CALC_ACC ='&ACCOUNT'
                      AND CUS.LIABILITY_NO = LIAB_ID)
/

PROMPT NEWLY ICTBS_TD_REDEMPTION

SELECT * FROM ICTBS_TD_REDEMPTION  WHERE BRANCH_CODE = '&BRANCH' AND CUST_AC_NO='&ACCOUNT';


PROMPT ACTB_DAILY_LOG FULL

SELECT * FROM ACTB_DAILY_LOG WHERE AC_NO='&ACCOUNT' OR RELATED_ACCOUNT='&ACCOUNT';

PROMPT ICTB_TD_LOG

SELECT * FROM ICTB_TD_LOG WHERE ACC='&ACCOUNT';

PROMPT MSTB_DLY_MSG_OUT

SELECT * FROM MSTB_DLY_MSG_OUT WHERE CUST_AC_NO = '&ACCOUNT';

SPOOL OFF
