SELECT CODE,GLCODE2,GLCODE1,BRANCH_CODE,DESCRIPTION,NVL(DR_OPEN,0) DR_OPEN,NVL(CR_OPEN,0) CR_OPEN,
NVL(DR_MOV,0) DR_MOV,NVL(CR_MOV,0) CR_MOV,
NVL(DR_CLOSING_BALANCE,0) DR_CLOSING_BALANCE,NVL(CR_CLOSING_BALANCE,0) CR_CLOSING_BALANCE
 FROM 
(SELECT '1' CODE,
GLCODE2,
GLCODE1,
BRANCH_CODE,
DESCRIPTION,
CASE
WHEN OPENING_BALANCE < '0' THEN
ABS(NVL(OPENING_BALANCE,0))
END DR_OPEN,
CASE
WHEN OPENING_BALANCE >= '0' THEN
ABS(NVL(OPENING_BALANCE,0))
END CR_OPEN,
MOV_BALANCE_dr DR_Mov,
MOV_BALANCE_cr CR_Mov,
CASE
WHEN CLOSINGING_BALANCE < '0' THEN
ABS(NVL(CLOSINGING_BALANCE,0))
END DR_CLOSING_BALANCE,
CASE
WHEN CLOSINGING_BALANCE >= '0' THEN
ABS(NVL(CLOSINGING_BALANCE,0))
END CR_CLOSING_BALANCE
from
(
select GL_CODE GLCODE2,SUBSTR(GL_CODE,1,5) glcode1,BRANCH_CODE,
(SELECT GL_DESC FROM GLTM_GLMASTER WHERE GL_CODE = T.GL_CODE) description,
DECODE(:PM_PERIOD_CODE,'M04',nvl('',0),(select  (SUM(NVL(CR_BAL_LCY,0)) - SUM(NVL(DR_BAL_LCY,0))) from gltb_gl_bal
 where GL_CODE = T.GL_CODE AND BRANCH_CODE = T.BRANCH_CODE AND PERIOD_CODE = :PM_PRE_CODE AND
FIN_YEAR = :PM_FINANCIAL_CYCLE))  OPENING_BALANCE,
--DECODE('M04','M04','0',(SUM(NVL(OPEN_CR_BAL_LCY,0))- SUM(NVL(OPEN_DR_BAL_LCY,0))))  OPENING_BALANCE,
SUM(NVL(Cr_MOV_lcy,0))  MOV_BALANCE_cr,
SUM(NVL(dr_MOV_lcy,0))  MOV_BALANCE_dr,
SUM(NVL(CR_BAL_LCY,0))-SUM(NVL(DR_BAL_LCY,0))  CLOSINGING_BALANCE  
from gltb_gl_bal T
where 
t.leaf = 'Y' AND
(gl_code BETWEEN NVL(:FROM_GL,GL_CODE) and NVL(:TO_GL,GL_CODE) )and
(Category IN ('1', '2','5','6','7','8','9') OR (Category IN ('3', '4') AND Ccy_Code = 'XAF')) and
(branch_code BETWEEN nvl(:FROM_branch,branch_code) and nvl(:TO_branch,branch_code) )and
PERIOD_CODE = :PM_PERIOD_CODE AND
FIN_YEAR = :PM_FINANCIAL_CYCLE
--PERIOD_CODE = 'M05' AND
--FIN_YEAR = 'FY2012'
group by GL_CODE, BRANCH_CODE,FIN_YEAR , PERIOD_CODE))
ORDER BY GLCODE2, BRANCH_CODE