SELECT ACCOUNT_NUMBER,
DESCRIPTION,
GLCODE1,
GL_INTERFACE,
CENTRAL_BANK_CODE,
RESIDENCE,
INSTITUTIONAL_UNIT,
substr(Loc_code,1,2) GEOGRAPHICAL_LOCATION,
Decode(ECONOMIC_ACTIVITY,'G','9',ECONOMIC_ACTIVITY) ECONOMIC_ACTIVITY,
SUM(DEBIT) DEBIT,
SUM(CREDIT) CREDIT,
PLACEMENT_DATE,
MATURITY_DATE,
CUSTOMER_ID,
BRANCH,
CCY,
RATE,
gl_closing_balance,
AMOUNT,
CB_SPECIFIC_CLIENTS,
Line, book_date
FROM vw_trial_balance A
GROUP BY
ACCOUNT_NUMBER,DESCRIPTION,GLCODE1,GL_INTERFACE,CENTRAL_BANK_CODE,RESIDENCE,INSTITUTIONAL_UNIT,Loc_code,ECONOMIC_ACTIVITY,PLACEMENT_DATE,MATURITY_DATE,CUSTOMER_ID,BRANCH,CCY,RATE,gl_closing_balance,AMOUNT,CB_SPECIFIC_CLIENTS,Line,book_date
ORDER BY ACCOUNT_NUMBER
