CREATE TABLE "XAFNFC"."STTM_CUSTOMER" 
   (	"CUSTOMER_NO" VARCHAR2(9), 
	"CUSTOMER_TYPE" CHAR(1), 
	"CUSTOMER_NAME1" VARCHAR2(105), 
	"ADDRESS_LINE1" VARCHAR2(105), 
	"ADDRESS_LINE3" VARCHAR2(105), 
	"ADDRESS_LINE2" VARCHAR2(105), 
	"ADDRESS_LINE4" VARCHAR2(105), 
	"COUNTRY" VARCHAR2(3), 
	"SHORT_NAME" VARCHAR2(20), 
	"NATIONALITY" VARCHAR2(3), 
	"LANGUAGE" VARCHAR2(3), 
	"EXPOSURE_COUNTRY" VARCHAR2(3), 
	"LOCAL_BRANCH" VARCHAR2(3), 
	"LIABILITY_NO" VARCHAR2(9), 
	"UNIQUE_ID_NAME" VARCHAR2(20), 
	"UNIQUE_ID_VALUE" VARCHAR2(20), 
	"FROZEN" CHAR(1), 
	"DECEASED" CHAR(1), 
	"WHEREABOUTS_UNKNOWN" CHAR(1), 
	"CUSTOMER_CATEGORY" VARCHAR2(10), 
	"HO_AC_NO" VARCHAR2(105), 
	"RECORD_STAT" CHAR(1), 
	"AUTH_STAT" CHAR(1), 
	"MOD_NO" NUMBER(4,0), 
	"MAKER_ID" VARCHAR2(12), 
	"MAKER_DT_STAMP" DATE, 
	"CHECKER_ID" VARCHAR2(12), 
	"CHECKER_DT_STAMP" DATE, 
	"ONCE_AUTH" CHAR(1) DEFAULT 'N', 
	"FX_CUST_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"OVERALL_LIMIT" NUMBER(24,3), 
	"FX_CLEAN_RISK_LIMIT" NUMBER(24,3), 
	"CREDIT_RATING" VARCHAR2(10), 
	"REVISION_DATE" DATE, 
	"LIMIT_CCY" VARCHAR2(3), 
	"CAS_CUST" CHAR(1), 
	"LIAB_NODE" VARCHAR2(105), 
	"SEC_CUST_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"SEC_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"SEC_CUST_PSTL_RISK_LIMIT" NUMBER(22,3), 
	"SEC_PSTL_RISK_LIMIT" NUMBER(22,3), 
	"LIAB_BR" VARCHAR2(3), 
	"PAST_DUE_FLAG" VARCHAR2(1), 
	"DEFAULT_MEDIA" VARCHAR2(15), 
	"SSN" VARCHAR2(11), 
	"SWIFT_CODE" VARCHAR2(12), 
	"LOC_CODE" VARCHAR2(3), 
	"SHORT_NAME2" VARCHAR2(20), 
	"UTILITY_PROVIDER" VARCHAR2(1) DEFAULT 'N', 
	"UTILITY_PROVIDER_ID" VARCHAR2(35), 
	"RISK_PROFILE" VARCHAR2(20), 
	"DEBTOR_CATEGORY" VARCHAR2(10), 
	"FULL_NAME" VARCHAR2(105), 
	"UDF_1" VARCHAR2(150), 
	"UDF_2" VARCHAR2(150), 
	"UDF_3" VARCHAR2(150), 
	"UDF_4" VARCHAR2(150), 
	"UDF_5" VARCHAR2(150), 
	"AML_REQUIRED" CHAR(1), 
	"AML_CUSTOMER_GRP" VARCHAR2(9), 
	"MAILERS_REQUIRED" CHAR(1), 
	"GROUP_CODE" VARCHAR2(10), 
	"EXPOSURE_CATEGORY" VARCHAR2(20), 
	"CUST_CLASSIFICATION" VARCHAR2(20), 
	"CIF_STATUS" VARCHAR2(20), 
	"CIF_STATUS_SINCE" DATE, 
	"CHARGE_GROUP" VARCHAR2(10), 
	"INTRODUCER" VARCHAR2(9), 
	"CUST_CLG_GROUP" VARCHAR2(10), 
	"CHK_DIGIT_VALID_REQD" VARCHAR2(1), 
	"ALG_ID" VARCHAR2(20), 
	"FT_ACCTING_AS_OF" VARCHAR2(1), 
	"UNADVISED" VARCHAR2(1) DEFAULT 'N', 
	"TAX_GROUP" VARCHAR2(10), 
	"CONSOL_TAX_CERT_REQD" VARCHAR2(1), 
	"INDIVIDUAL_TAX_CERT_REQD" VARCHAR2(1), 
	"CLS_CCY_ALLOWED" VARCHAR2(1) DEFAULT 'D', 
	"CLS_PARTICIPANT" VARCHAR2(1), 
	"FX_NETTING_CUSTOMER" VARCHAR2(9), 
	"RISK_CATEGORY" VARCHAR2(4), 
	"FAX_NUMBER" VARCHAR2(105), 
	"EXT_REF_NO" VARCHAR2(20), 
	"CRM_CUSTOMER" VARCHAR2(1), 
	"ISSUER_CUSTOMER" VARCHAR2(1), 
	"TREASURY_CUSTOMER" VARCHAR2(1), 
	"CIF_CREATION_DATE" DATE, 
	"WHT_PCT" NUMBER, 
	"RP_CUSTOMER" VARCHAR2(1), 
	"GENERATE_MT920" VARCHAR2(1), 
	"KYC_DETAILS" VARCHAR2(1), 
	"STAFF" VARCHAR2(1), 
	"KYC_REF_NO" VARCHAR2(16), 
	"UTILITY_PROVIDER_TYPE" VARCHAR2(35), 
	"JOINT_VENTURE" VARCHAR2(1) DEFAULT 'N', 
	"JV_LIMIT_TRACKING" VARCHAR2(1) DEFAULT 'N', 
	"PRIVATE_CUSTOMER" VARCHAR2(1), 
	 CONSTRAINT "PK01_STTM_CUSTOMER" PRIMARY KEY ("CUSTOMER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE INDEX "XAFNFC"."IX02_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("LOCAL_BRANCH", "CUSTOMER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE UNIQUE INDEX "XAFNFC"."UI01_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("UTILITY_PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE UNIQUE INDEX "XAFNFC"."UI02_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE UNIQUE INDEX "XAFNFC"."PK01_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("CUSTOMER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE INDEX "XAFNFC"."I04_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("EXT_REF_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 106496 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE INDEX "XAFNFC"."UI05_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("SHORT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 106496 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE INDEX "XAFNFC"."UI03_STTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("UNIQUE_ID_NAME", "UNIQUE_ID_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 106496 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  CREATE INDEX "XAFNFC"."IX0HSTTM_CUSTOMER" ON "XAFNFC"."STTM_CUSTOMER" ("LIABILITY_NO", (-1)) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT" ;
  ALTER TABLE "XAFNFC"."STTM_CUSTOMER" ADD CONSTRAINT "PK01_STTM_CUSTOMER" PRIMARY KEY ("CUSTOMER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDFLT"  ENABLE;
  GRANT SELECT ON "XAFNFC"."STTM_CUSTOMER" TO "NFCREAD";
  GRANT SELECT ON "XAFNFC"."STTM_CUSTOMER" TO "NFCEOD";
  GRANT SELECT ON "XAFNFC"."STTM_CUSTOMER" TO "SMSUSR";
  GRANT SELECT ON "XAFNFC"."STTM_CUSTOMER" TO "NFCONLINE";
